version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    versioning-strategy: increase
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      prod-dependencies:
        dependency-type: 'production'
      dev-dependencies:
        dependency-type: 'development'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'
