name: '📸 Screenshot'

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.1-jammy
    env:
      HOME: /root
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Create the screenshot
        run: pnpm exec playwright test --project=chromium tests/e2e/screenshot.spec.ts

      - name: Commit screenshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update demo screenshot'
          file_pattern: 'docs/demo.png'
